server:
  port: 8080
  servlet:
    context-path: /contest-programing

spring:
  datasource:
    url: "jdbc:mariadb://14.165.105.186:3306/contest_programing"
    username: root
    password: lenovothinkpadx230
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: "Yge86fb6CnZTXqgPy57L8WuZyirLw0NUucUJJBaq3V3RTEnFF7gMg2Qp2bVCA1Ze"
