server:
  port: 8080
  servlet:
    context-path: /contest-programing

spring:
  datasource:
    url: "jdbc:mariadb://14.165.105.186:3306/contest_programing"
    username: root
    password: lenovothinkpadx230
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/, classpath:/static/uploads/

jwt:
  secret-key: "Yge86fb6CnZTXqgPy57L8WuZyirLw0NUucUJJBaq3V3RTEnFF7gMg2Qp2bVCA1Ze"
